export const AppError = {
    WRONG_CREDENTIALS: 'Данные не совпадают!',
    INVALID_JWT: 'Неправильный токен!',
    CATEGORY_NOT_FOUND: 'Категория не найдена!',
    CHECKPOINT_NOT_FOUND: 'Пункт пропуска не найден!',
    FACILITY_NOT_FOUND: 'Объект обслуживания не найден!',
    FILE_TYPE_NOT_FOUND: 'Тип файла не найден!',
    GROUP_NOT_FOUND: 'Группа не найдена!',
    ORDER_NOT_FOUND: 'Заказ не найден!',
    ORDER_STATUS_NOT_FOUND: 'Статус заказа не найден!',
    ORGANIZATION_NOT_FOUND: 'Организация не найдена!',
    ORGANIZATION_TYPE_NOT_FOUND: 'Тип организации не найден!',
    PERMISSION_NOT_FOUND: 'Разрешение не найдено!',
    PERSON_NOT_FOUND: 'Данные пользователя не найдены!',
    PRIORITY_NOT_FOUND: 'Приоритет не найден!',
    REPORT_NOT_FOUND: 'Отчет не найден!',
    ROLE_NOT_FOUND: 'Роль не найдена!',
    ROLE_PERMISSION_NOT_FOUND: 'Запись не найдена!',
    TASK_NOT_FOUND: 'Задача не найдена!',
    TRANSACTION_HISTORY_NOT_FOUND: 'Запись в истории не найдена!',
    USER_EXECUTOR_NOT_FOUND: 'Пользователь (исполнитель) не найден!',
    USER_CREATOR_NOT_FOUND: 'Пользователь (создатель) не найден!',
    USER_NOT_FOUND: 'Пользователь не найден!',
    USER_LOGIN_EXISTS: 'Пользователь с таким логином уже существует!',
}